# Generated by Django 5.0.6 on 2024-07-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ticket_status_ticket_time_estimate_ticket_time_spent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='sender',
        ),
    ]
