# Generated by Django 5.0.6 on 2024-07-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_workhour_ticket_status_ticket_time_estimate_and_more'),
        ('myapp', '0005_rename_user_chatmessage_sender'),
    ]

    operations = [
    ]
