# Generated by Django 5.0.6 on 2024-07-27 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_merge_20240723_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=False)),
                ('notified_employees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket')),
            ],
        ),
    ]
