# Generated by Django 5.0.6 on 2024-07-27 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_ticketnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketnotification',
            name='notified_employees',
        ),
        migrations.AddField(
            model_name='ticketnotification',
            name='notified_employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
