# Generated by Django 5.0.6 on 2024-07-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_ticketnotification_notified_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketnotification',
            name='notified_employee',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
