# Generated by Django 5.0.6 on 2024-07-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_notification_delete_ticketnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='TicketNotification',
        ),
    ]
