# Generated by Django 5.0.6 on 2024-07-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_notification_ticketnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketnotification',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ticket'),
        ),
    ]
