# Generated by Django 5.0.6 on 2024-07-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_profile_picture'),
        ('myapp', '0012_alter_ticketnotification_ticket'),
    ]

    operations = [
    ]
